/* eslint-disable import/no-anonymous-default-export */
export default {
  en: {
    serviceChargeTypeName: "Service Charge Type Name",
    or: "OR",
    totalCharges: "Total Charges",
    loiPreview: "Loi Preview",
    chargeName: "Charge Name",
    amount: "Amount",
    iCard: "Identity Card",
    ddNo: "Demand Draft Number",
    viewCertificate: "View Certificate",
    ddDate: "Demand Draft Date",
    AptBook: "Appointment Slot Booking",
    streetVendorQuestion: "Street Vendor Question",
    applicantName: "Applicant Name",
    receiptDate: "Receipt Date",
    receiptNumber: "Receipt Number",
    receiptAmount: "Receipt Amount",
    loiRecord: "Loi Record",
    loiGeneration: "  LOI Generation",
    loiPrint: "  LOI Print",
    loiCollection: "LOI Collection",
    paymentMode: "Payment Mode",
    paymentType: "Payment Type",
    receiptModeDetails: "Receipt Mode Details",
    type: "commonLabels",
    search: "Search",
    loiNO: "LOI NO.",
    loiDetails: "LOI Details",
    and: "And",
    loiDate: "LOI Date",
    applicationNo: "Application NO.",
    loiCollection: "LOI Collection",
    rate: "Rate",
    amount: "Amount",
    total: "Total",
    totalInWords: "Total Charges in Words",
    licenseType: "License Type",
    durationOfLicenseValidity: " Duration of License Validity (in year)",
    checkFormLicenseValidityForm: " Check for License Validity From",
    hawkerType: "Hawker Type",
    serviceCharge: "Service Charges",
    licenseValidity: "License Validity",
    applicantDetails: "Applicant Details",
    applicantDetails: "Applicant Details",
    chargesDetails: "Charges Details",
    dateOfIssuance: "Date of Issuance",
    calendarYear: "Calendar Year",
    financialYear: "Financial Year",
    generateLoi: "Generate LOI",
    previewLoi: "Preview LOI",
    verifyLoi: "Verify LOI",
    HMS: "Street Vendor Management System",
    streetVendorManagmentSystem: "Street Vendor Management System",
    siteVisitPhotoUpload: "Upload Photos of a Site Visit",
    streetVendorInformation: "Street Vendor Information",
    businessHawkinglocation:
      "who is operating the business at the hawking location ?",
    remark: "Remark",
    dashboard: "Pimpri-Chinchwad Municipal Corporation Dashboard",
    master: "Masters",
    roadWithBusinessLocation: "Road Width at Business Location? (in feet)",
    streetVendorPhoto: "Photo",
    inFeet: "in feet",

    streetVendorThumb1: "Biometric Impression of Thumb 1",
    streetVendorThumb2: "Biometric Impression of Thumb 2",
    transactions: "Transactions",
    report: "Reports",
    masterPath: "Hawker Management System / masters",
    transactionPath: "Legal Case / Transaction ",
    reportPath: "Legal Case / Report ",
    inspectionSellingGoods:
      "Did the inspection discover that the applicant is selling goods at the specified location?",
    HMS: "Street Vendor Management System",
    businessTrafficCongestion:
      "Does the business currently cause traffic congestion ?",
    dashboard: "Pimpri-Chinchwad Municipal Corporation Dashboard",
    master: "Masters",
    transactions: "Transactions",
    report: "Reports",
    siteVisit: "Site Visit",
    masterPath: "Hawker Management System / masters",
    transactionPath: "Legal Case / Transaction ",
    reportPath: "Legal Case / Report ",
    master: "Masters",
    hawkerType: "Street Vendor Type",
    masterPath: "SkySign/ Master",
    masterPath: "FIRE BRIGADE SYSTEM / masters",
    religionPath: "Street Vendor Management System / masters / Religion",
    hawkerTypePath:
      "Street Vendor Management System / masters / Street Vendor Type",
    businessTypeMasterPath:
      "Street Vendor Management System / masters / Business Type Master",
    businessSubTypePath:
      "Street Vendor Management System / masters / Business Sub Type",
    titlePath: "Street Vendor Management System / masters / Title",
    itemMasterPath: "Street Vendor Management System / masters / Item Master",
    itemCategoryMasterPath:
      "Street Vendor Management System / masters / Item Category Master",
    castCategoryPath:
      "Street Vendor Management System / masters / Caste Category",
    castMasterPath: "Street Vendor Management System / masters / Cast Master",
    hawkingZonePath: "Street Vendor Management System / masters / Hawking Zone",
    subCastMasterPath:
      "Street Vendor Management System / masters / Sub Caste Master",
    licenseValidityPath:
      "Street Vendor Management System / masters / License Validity",
    penaltyPath: "Street Vendor Management System / masters / Penalty",
    bankMasterPath: "Street Vendor Management System / masters /Bank Master",
    hawkingZoneWiseFacilitiesPath:
      "Street Vendor Management System / masters / Hawking Zone Wise Facilities",
    taxTypeMasterPath:
      "Street Vendor Management System / masters / Tax Type Master",
    taxNameMasterPath:
      "Street Vendor Management System / masters / Tax Name Master",
    serviceTaxCollectionCyclePath:
      "Street Vendor Management System / masters / Service Tax Collection Cycle",
    taxRateChartMasterPath:
      "Street Vendor Management System / masters / Tax Rate Chart Master",
    noHawkingZonePath:
      "Street Vendor Management System / masters / No Hawking Zone",
    hawkerMasterPath:
      "Street Vendor Management System / masters / Street Vendor Master",
    ward: "Ward",
    zone: "Zone",
    religion: "Religion",
    hawkerType: "Street Vendor Type",
    businessTypeMaster: "Business Type Master",
    businessSubType: "Business Sub Type",
    title: "Title",
    itemMaster: "Item Master",
    itemCategoryMaster: "Item Category Master",
    castCategory: "Caste Category",
    castMaster: "Caste Master",
    hawkingZone: "Hawking Zone",
    subCastMaster: "Sub Caste Master",
    licenseValidity: "License Validity",
    penalty: "Penalty",
    bankMaster: "Bank Master",
    hawkingZoneWiseFacilities: "Hawking Zone Wise Facilities",
    taxTypeMaster: "Tax Type Master",
    taxNameMaster: "Tax Name Master",
    serviceTaxCollectionCycle: "Service Tax Collection Cycle",
    taxRateChartMaster: "Tax Rate Chart Master",
    noHawkingZone: "No Hawking Zone",
    hawkerMaster: "Street Vendor Master",
    streetvendorApplicantCategory: "Streetvendor Applicant Categor",
    srNo: "Sr. No",
    actions: "Actions",
    srNo: "Sr No",
    hawkerTypePrefix: "Street Vendor Type Prefix",
    fromDate: "From Date",
    toDate: "To Date",
    hawkerType: "Street Vendor Type",
    remark: "Remark",
    actions: "Actions",
    actions: "Actions",
    remark: "Remark",
    zoneName: "Zone Name",
    hawkingZoneInfo: "Street Vendor Zone Info",
    itemName: "Item Name",
    noOfHawkersPresent: "No Of Street Vendors Present",
    capacityOfHawkingZone: "Capacity Of Street Vendor Zone",
    declarationOrder: "Declaration Order",
    declarationOrderNo: "Declaration Order No",
    declarationDate: "Declaration Date",
    areaName: "Area Name ",
    hawkingZoneName: "Street Vendor Zone Name",
    streetvendorModeName: "Street Vendor Mode Name",
    citySurveyNo: "City Survey No ",
    gisId: "GIS Id",
    hawkingZonePrefix: "Street Vendor Zone Prefix",
    constraint: "Constraint",
    serviceTaxCollectionCyclePrefix: "Service-Tax Collection Cycle Prefix",
    hawkerTypeName: "Street Vendor Type Name",
    licenseValidityPrefix: "License Validity Prefix",
    noHawkingZoneName: "No Street Vendor Zone Name",
    noHawkingZoneprefix: "No Street Vendor Zone Prefix",
    itemCategoryPrefix: "Item Category Prefix",
    itemCategory: "Item Category",
    hawkingZoneWiseFacilitiesPrefix:
      "Street Vendor Zone Wise Facilities Prefix",
    facilities: "Facilities",
    hawkingZoneName: "Street Vendor Zone Name",
    hawkerPrefix: "Street Vendor Prefix",
    citySurveyNo: "City Survey No",
    firstName: "First Name",
    transactions: "Transactions",
    transactionPath: "SkySign / Transaction",
    issuanceOfHawkerLicensePath:
      "Street Vendor Management System / issuanceOfStreetVendorLicense",
    siteVisitPath: "Street Vendor Management System / Site Visit",
    taskTransfer: "Street Vendor Management System / Task Transfer",
    viewLocationOnMap: "View Location On Map",
    issuanceOfHawkerLicensePath:
      "Street Vendor Management System / issuanceOfStreetVendorLicense",
    siteVisitPath: "Street Vendor Management System / Site Visit",
    taskTransfer: "Street Vendor Management System / Task Transfer",
    viewLocationOnMap: "View Location On Map",
    department: "Department Name",
    issuanceOfHawkerLicense: "Issuance of Street Vendor License",
    taskTransfer: "Task Transfer",
    applicantType: "Applicant Type",
    basicApplicationDetails: "Basic Application Details",
    serviceName: "Service Name ",
    applicationNumber: "Application Number",
    applicationDate: "Application Date",
    citySurveyNo: "City Survey No",
    hawkingZoneName: "Street Vendor Zone Name ",
    areaName: "Area Name",
    basicApplicationDetails: "Basic Application Details",
    hawkerDetails: "Street Vendor Details",
    addressOfHawker: "Address",
    aadharAuthentication: "Aadhaar Authentication",
    aadhaarNo: "Aadhaar No",
    streetvendorModeName: "Street Vendor Mode Name",
    additionalDetails: "Business Details",
    documentsUpload: "Documents Upload",
    title: "Title ",
    firstName: "First Name ",
    middleName: "Middle Name ",
    lastName: "Last Name / Surname",
    gender: "Gender",
    religion: "Religion",
    caste: "Caste",
    subCast: "Sub Caste",
    dateOfBirth: "Date of Birth ",
    age: "Age ",
    mobile: "Mobile No. ",
    emailAddress: "Email Address",
    disability: "Disability",
    rationCardNo: "Ration Card No",
    yes: "Yes",
    no: "No",
    typeOfDisability: "Type Of Disability",
    oldSVSLicenseDate: "Old License Date",
    oldLicenseNo: "Old License Number",
    currentAddressofHawker: "Current Address",
    citySurveyNumber: "City Survey Number ",
    areaName: "Area Name ",
    landmarkName: "Landmark ",
    villageName: "Village Name ",
    cityName: "City Name ",
    state: "State ",
    pinCode: "Pin Code ",
    lattitude: "Lattitude ",
    logitude: "Longitude ",
    permanentPostalAddressOfHawker: "Permanent/Postal Address",
    permanentAddressAsTheCorrespondenceAddress:
      "Permanent Address As The Correspondence Address",
    citySurveyNumber: "City Survey Number",
    aadharAuthentication: "Aadhaar Authentication",
    verfiyOtp: "Verify OTP",
    sendOTP: "Send OTP",
    aadhaarOtpVerified: "aadhaar otp verified successfully",
    verfiyOtp: "Verify OTP",
    otpVerification: "OTP VERIFICATION",
    verifiyOTP: "Verifiy OTP",
    resendOTP: "Resend OTP",
    sendOTPMessage:
      "a 6 digit one-time password is sent to your registered number",
    wardNo: "Ward No",
    wardName: "Ward Name",
    natureOfBusiness: "Nature of Business",
    hawkingDurationDaily: "Street Vendor Duration Daily",
    item: "Item",
    periodOfResidenceInMaharashtra: "Period of Residence In Maharashtra",
    periodOfResidenceInPcmc: "Period of Residence In PCMC",
    bankName: "Bank Name",
    branchName: "Branch Name",
    bankAccountNo: "Bank Account No",
    ifscCode: "IFSC Code",
    hawkerType: "Street Vendor Type",
    bankDetails: "Bank Details",
    documentUpload: "Documents Upload ",
    adharCard: "Aadhaar Card ",
    panCard: "Pan Card ",
    rationCard: "Ration Card ",
    disablityCretificatePhoto: "Disability Certificate ",
    otherDocumentPhoto: "Other Documents ",
    affidaviteOnRS100StampAttachement:
      "Affidavite On RS.100 Stamp Attachement ",
    selectDate: "Please select a date",
    selectTitle: "Please select a title",
    enterFName: "Please enter first name ",
    enterMName: "Please enter middle name ",
    enterLName: "Please enter last name ",
    enterArea: "Please enter area ",
    enterRoadName: "Please enter road name ",
    enterLandmark: "Please enter a landmark ",
    enterCity: "Please enter a city ",
    enterPinCode: "Please enter a pincode ",
    enterPhoneNo: "Please enter a phone no. ",
    enterMobileNo: "Please enter a mobile no. ",
    enterEmailAddress: "Please enter an e-mail. ",
    enteraadhaarNo: "Please enter an aadhaar no. ",
    enterpanNo: "Please enter an pan no. ",
    enterRemarks: "Please enter a remark. ",
    attachFile: "Attach File",
    srNo: "Sr. No",
    actions: "Actions",
    tax: "Tax",
    streetVendorType: "Street Vendor Type",
    waterAmount: "Water Amount",
    propertyTaxNumber: "Property Tax No",
    waterConsumerNo: "Water Consumer No",
    proprtyAmount: "Property Amount",
    viewBill: "View Bill",
    payBill: "Pay Bill",
    PropertyAndWaterTaxes: "Taxes",
    propertyTaxes: "Property Taxes",
    viewBill: "View Bill",
    pay: "Pay",
    waterTaxes: "Water Taxes",
    areaOfStreetvendor: "Area of Streetvendor",
    education: "Education",
    viewLocationOnMap: "view location on map",
    voterNameYN: "the name of applicant is present in Voters list?",
    voterId: "Voter Identity No.",
    additionalLabour: "are additional workers present at the site?",
    maharashtra: "Maharashtra",
    oldLicenseDate: "Old License Date",
    pimpriChinchwad: "Pimpri Chinchwad",
    applicantItsSelf: "Applicant its self",
    withHelpofFamilyMembers: "with help of family members",
    byKeepingservant: "by keeping servant",
    roadWithAtBusinessLocation: "road width at the business location",
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",
    fileSizeInstrction: "file size should not be greater than 2 mb ",

    // Validations
    citySurveyNoValdation: "city survey number is required !!!",
    citySurveyNoValdationA: "city survey number must be number !!!",
    areaNameValidation: "area name selection is required !!!",
    hawkingZoneNameValidation: "hawking zone name selection is required !!!",
    titleValidation: "title selection is required !!!",
    firstNameValidation: "first name is required !!!",
    middleNameValidation: "middle name is required !!!",
    lastNameValidation: "last name is required !!!",
    genderValidation: "gender selection is required !!!",
    religionValidation: "religion selection is required !!!",
    casteValidation: "caste selection is required !!!",
    subCasteValidation: "sub caste selection is required !!!",
    dateOfBirthValidation: "date of birth is required  !!!",
    ageValidation: "age is required !!!",
    mobileNovalidation: "mobile number is required  !!!",
    rationCardNoValidation: "ration card number is required !!!",
    applicantTypeValidation: "applicant type selection is required !!!",
    emailIdValidation: "email id is required !!!",
    emailIdValidationA: "please enter valid email address !!!",
    landmarkNameValidation: "landmark name selection is required !!!",
    villageNameValidation: "village name selection is required !!!",
    cityNameValidation: "city name is required !!!",
    stateNameValidation: "state name is required !!!",
    pinCodeValidation: "pin code selection is required !!!",
    lattitudeValidation: "latitude is required !!!",
    logitudeValidation: "longitude s required !!!",
    aadharNumberValidation: "aadhaar number is required !!!",
    propertyTaxNumberValidation: "property Tax Number is required !!!",
    waterConsumerNoValidation: "water Consumer Number is required !!!",
    proprtyTaxAmountNumberValidation: "property amount is required !!!",
    waterTaxAmountValidation: "water tax amount is required !!!",
    streetvendorModeNameValidation:
      "street vendor Mode Name selection is required !!!",
    wardNameValidation: "ward name selection is required !!!",
    natureOfBusinessValidation: "nature of business name is required !!!",
    hawkingDurationDailyValidation:
      "street vendor duration daily selection is required !!!",
    hawkerTypeValidation: "street vendor type selection is required !!!",
    itemValidation: "item selection is required !!!",
    educationValidation: "education selection is required !!!",
    areaOfStreetvendorValidation: "area of street vendor is required !!!",
    periodOfResidenceInPCMCValidation:
      "period of residence in PCMC is required !!!",
    periodOfResidenceInMaharashtraValidation:
      "period of residence in maharashtra is required !!!",
    voterIdValidation: "Voter Identity Number is required !!!",
    voterNameYNValidation: "selection is required !!!",
    bankMasterValidation: "bank name selection is required !!!",
    bankAccountNoValidation: "bank account number is required !!!",
    ifscCodeValidation: "IFSC code is required !!!",
    branchNameValidation: "branch name is required !!!",
    aadhaarCardPhotoValidation: "aadhaar card is required !!!",
    panCardPhotoValidation: "pan card is required !!!",
    rationCardPhotoValidation: "ration card is required !!!",
    disablityCertificatePhotoValidation:
      "disablity certificate is required !!!",
    affidaviteOnRS100StampAttacheValidation:
      "affidavite on rs100 statmp attachement is required !!!",

    // typeOfDisabilityValidation: "type of disability is required !!!",
    otherDocumentPhotoValidation: "other document is required !!!",
    oldLicenseNoValidation: "old license number is required !!!",
    oldLicenseDateValidation: "old license date is required !!!",

    documentUpload1: "Doucument Upload",
    documentUploadSuccessfully: "document uploaded successfully !!!",
    delete: "delete",
    areYouWantDelete: "are you sure you want to delete the file ?",
    fileDeletedSuccessfully: "file deleted successfully !!!",
    fileIsSafe: "file is safe",
    somethingWentWrong: "something went wrong ..!!!",
  },
  mr: {
    receiptModeDetails: "Receipt Mode Details",
    chargeName: "Charge Name",
    loiPreview: "Loi Preview",
    iCard: "Identity Card",
    viewCertificate: "View Certificate",
    amount: "Amount",
    streetVendorQuestion: "Street Vendor Question",
    or: "OR",
    loiRecord: "loiRecord",
    loiNO: "LOI NO.",
    loiGeneration: "  LOI Generation",
    loiPrint: "  LOI Print",
    applicantName: "Applicant Name",
    loiCollection: "LOI Collection",
    search: "Search",
    and: "And",
    paymentMode: "Payment Mode",
    paymentType: "Payment Type",
    loiDetails: "LOI Details",
    loiDate: "LOI Date",
    applicationNo: "Application NO.",
    loiCollection: "LOI Collection",
    rate: "Rate",
    amount: "Amount",
    total: "Total",
    totalInWords: "Total Charges in Words",
    licenseType: "License Type",
    durationOfLicenseValidity: " Duration of License Validity (in year)",
    hawkerType: "Hawker Type",
    licenseValidity: "License Validity",
    applicantDetails: "Applicant Details",
    paymetMode: "Payment Mode",
    dateOfIssuance: "date of issuance",
    calendarYear: "calendar year",
    chargesDetails: "Charges Details",
    serviceCharge: "Service Charges",
    financialYear: "financial year",
    checkFormLicenseValidityForm: " Check for license validity from",
    generateLoi: "Generate LOI",
    previewLoi: "Preview LOI",
    verifyLoi: "Verify LOI",
    serviceChargeTypeName: "Service Charge Type Name",
    totalCharges: "Total Charges",
    receiptAmount: "पावती रक्कम",
    receiptNumber: "पावती क्रमांक",
    receiptDate: "पावती तारीख",
    ddDate: "डिमांड ड्राफ्ट तारीख",
    ddNo: "डिमांड ड्राफ्ट क्रमांक",
    AptBook: "अपॉइंटमेंट स्लॉट बुकिंग",
    streetVendorManagmentSystem: "पथविक्रेता व्यवस्थापन प्रणाली",
    HMS: "पथविक्रेता व्यवस्थापन प्रणाली",
    inFeet: "रुंदीमध्ये",
    streetVendorType: "पथविक्रेत्याचा प्रकार",
    oldLicenseDate: "जुनी परवाना तारीख",
    siteVisitPhotoUpload: "साइट भेटीचे फोटो अपलोड करा",
    streetVendorThumb1: "बायोमेट्रिक अंगठ्याचा ठसा 1",
    streetVendorThumb2: "बायोमेट्रिक अंगठ्याचा ठसा 2",
    businessTrafficCongestion: "व्यवसायामुळे सध्या वाहतूक कोंडी होते का?",
    remark: "Remark",
    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    roadWithBusinessLocation: "व्यवसायाच्या ठिकाणी रस्त्याची रुंदी (फूटमध्ये)",
    streetVendorInformation: "पथविक्रेता माहिती",
    businessHawkinglocation: "फेरीवाल्यांच्या ठिकाणी व्यवसाय कोण चालवत आहे?",
    applicantItsSelf: "अर्जदार स्वतः",
    withHelpofFamilyMembers: "कुटुंबातील सदस्यांच्या मदतीने",
    streetVendorPhoto: "फोटो",
    byKeepingservant: "नोकर ठेवून",
    inspectionSellingGoods:
      "तपासणीत असे आढळून आले की अर्जदार विनिर्दिष्ट ठिकाणी वस्तू विकत आहे?",
    master: "मास्टर्स",
    transactions: "व्यवहार",
    report: "अहवाल",
    masterPath: "अग्निशमन यंत्रणा / मास्टर ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",
    reportPath: "कायदेशीर प्रकरण/ अहवाल ",
    hawkerType: "पथविक्रीचा प्रकार",
    department: "Department Name",
    master: "मास्टर्स",
    transactions: "व्यवहार",
    report: "अहवाल",
    ward: "प्रभाग",
    zone: "झोन",
    religionPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / धर्म",
    hawkerTypePath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / पथविक्रेता प्रकार",
    businessTypeMasterPath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / व्यवसाय प्रकार मास्टर",
    businessSubTypePath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / व्यवसाय उपप्रकार",
    titlePath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / शीर्षक",
    itemMasterPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / वस्तु मास्टर",
    itemCategoryMasterPath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / वस्तु श्रेणी मास्टर",
    castCategoryPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / कास्ट श्रेणी",
    castMasterPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / कास्ट मास्टर",
    hawkingZonePath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर /  हॉकिंग झोन",
    subCastMasterPath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / सब कास्ट मास्टर",
    licenseValidityPath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / परवाना वैधता",
    penaltyPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / दंड",
    bankMasterPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / बँक मास्टर",
    hawkingZoneWiseFacilitiesPath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / हॉकिंग झोननिहाय सुविधा",
    taxTypeMasterPath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / कर प्रकार मास्टर",
    taxNameMasterPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / कर नाव मास्टर",
    serviceTaxCollectionCyclePath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / सेवा कर संकलन सायकल",
    taxRateChartMasterPath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / कर दर चार्ट मास्टर",
    noHawkingZonePath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / हॉकिंग झोन नाही",
    hawkerMasterPath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / पथविक्रेता मास्टर",
    streetvendorApplicantCategory: "Streetvendor Applicant Categor",
    religion: "धर्म",
    hawkerType: "पथविक्रीचा प्रकार",
    businessTypeMaster: "व्यवसायचा प्रकार मास्टर",
    businessSubType: "व्यवसाय उपप्रकार",
    title: "शीर्षक",
    itemMaster: "वस्तु मास्टर",
    itemCategoryMaster: "वस्तु श्रेणी मास्टर",
    castCategory: "कास्ट श्रेणी",
    castMaster: "कास्ट मास्टर",
    hawkingZone: "पथविक्रेत्याचा झोन",
    subCastMaster: "सब कास्ट मास्टर",
    licenseValidity: "परवाना वैधता",
    penalty: " दंड",
    bankMaster: "बँक मास्टर",
    hawkingZoneWiseFacilities: "पथविक्रेत्याच्या झोननिहाय सुविधा",
    taxTypeMaster: " कर प्रकार मास्टर",
    taxNameMaster: "कर नाव मास्टर",
    serviceTaxCollectionCycle: "सेवा कर संकलन सायकल",
    taxRateChartMaster: "कर दर चार्ट मास्टर",
    noHawkingZone: "पथविक्रेत्याला झोन नाही",
    hawkerMaster: "पथविक्रेत्याचा मास्टर",
    courtName: "न्यायालयाचे नाव",
    roadName: "रस्त्याचे नाव",
    address: "पत्ता",
    landmark: "जवळची खूण",
    cityOrVillage: "शहर / गाव",
    pincode: "Pin Code",
    srNo: "अनुक्रमांक",
    actions: "क्रिया ",
    srNo: "अनु. क्र",
    hawkerTypePrefix: "पथविक्रेत्याचा उपसर्ग प्रकार ",
    fromDate: "या तारखेपासून",
    toDate: "आजपर्यंत",
    hawkerType: "पथविक्रीचा प्रकार",
    remark: "शेरा",
    roadWithAtBusinessLocation: "व्यवसायाच्या ठिकाणी रस्त्याची रुंदी",
    actions: "क्रिया",
    remark: "शेरा",
    zoneName: "पथविक्रेत्याचे नाव",
    hawkingZoneInfo: "पथविक्रेत्याच्या झोनची माहिती",
    itemName: "वस्तु",
    noOfHawkersPresent: "उपस्थित हॉकर्सची संख्या",
    capacityOfHawkingZone: "पथविक्रेत्याच्या झोनची क्षमता",
    declarationOrder: "घोषणा आदेश",
    declarationOrderNo: "घोषणा आदेश क्र",
    declarationDate: "घोषणा तारीख",
    areaName: "क्षेत्राचे नाव",
    hawkingZoneName: "पथविक्रीच्या झोनचे नाव",
    streetvendorModeName: "पथविक्रीच्या व्यवसायाचे स्वरूप",
    citySurveyNo: "सिटी सर्व्हे क्र ",
    gisId: "GIS आयडी",
    serviceTaxCollectionCyclePrefix: "सेवा कर संकलन चक्र उपसर्ग",
    hawkingZonePrefix: "पथविक्रेत्याच्या झोनचा उपसर्ग",
    hawkerTypeName: "पथविक्रीच्या प्रकाराचे नाव",
    licenseValidityPrefix: "परवाना वैधता उपसर्ग",
    noHawkingZoneName: "पथविक्रेत्याच्या झोनला नाव नाही",
    noHawkingZoneprefix: "पथविक्रेत्याच्या झोनचा उपसर्ग नाही",
    itemCategoryPrefix: "वस्तुच्या श्रेणीचा उपसर्ग",
    itemCategory: "वस्तुची श्रेणी",
    hawkingZoneWiseFacilitiesPrefix: "हॉकिंग झोननिहाय सुविधा उपसर्ग",
    facilities: "सुविधा",
    hawkingZoneName: "पथविक्रीच्या झोनचे नाव",
    hawkerPrefix: "पथविक्रेत्याचा उपसर्ग",
    citySurveyNo: "सिटी सर्व्हे क्र",
    add: "नवीन नोंदणी करा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",
    fileSizeInstrction: "फाइल आकार 2 mb पेक्षा जास्त नसावा",
    transactions: "व्यवहार",
    transactionPath: "परवाना/ व्यवहार ",
    issuanceOfHawkerLicense: "पथविक्रेता परवाना जारी करणे",
    siteVisit: "स्थळ भेट",
    citySurveyNo: "सिटी सर्व्हे क्र ",
    streetvendorModeName: "पथविक्रीच्या व्यवसायाचे स्वरूप",
    issuanceOfHawkerLicensePath:
      "पथविक्रेता व्यवस्थापन प्रणाली / पथविक्रेता परवाना जारी करणे",
    siteVisitPath: "पथविक्रेता व्यवस्थापन प्रणाली /साइटला भेट द्या",
    taskTransfer: "पथविक्रेता व्यवस्थापन प्रणाली / कार्य हस्तांतरण",
    viewLocationOnMap: "नकाशावर स्थान पहा",
    back: "मागे",
    next: "पुढे",
    issuanceOfHawkerLicense: "पथविक्रेता परवाना जारी करणे",
    taskTransfer: "कार्य हस्तांतरण",
    siteVisit: "साइटला भेट द्या",
    oldSVSLicenseDate: "जुन्या परवाण्याची तारीख",
    oldLicenseNo: "जुना परवाना क्रमांक",
    issuanceOfHawkerLicenseT: "पथविक्रेता परवाना जारी करणे",
    applicantType: "अर्जदाराचा प्रकार",
    basicApplicationDetails: "मूलभूत अर्ज तपशील",
    serviceName: "सेवेचे नाव ",
    applicationNumber: "अर्ज क्रमांक",
    applicationDate: "अर्जाची तारीख",
    citySurveyNo: "शहर सर्वेक्षण क्रमांक",
    hawkingZoneName: "पथविक्रीच्या झोनचे नाव",
    areaName: "क्षेत्राचे नाव",
    basicApplicationDetails: "मूलभूत अर्ज तपशील",
    hawkerDetails: "पथविक्रेत्याच्या तपशील",
    addressOfHawker: "पत्ता",
    aadharAuthentication: "आधार प्रमाणीकरण",
    aadhaarNo: "आधार क्रमांक",
    additionalDetails: "व्यवसाय तपशील",
    documentsUpload: "दस्तऐवज अपलोड",
    title: "शीर्षक",
    firstName: "पहिले नाव",
    middleName: "वडीलांचे/पतीचे नाव",
    lastName: "आडनाव",
    gender: "लिंग",
    religion: "धर्म",
    caste: "जात",
    subCast: "पोटजात",
    dateOfBirth: "जन्मतारीख ",
    age: "वय",
    mobile: "दूरध्वनी क्रमांक",
    emailAddress: "ई-मेल आयडी ",
    disability: "दिव्यांग",
    rationCardNo: "शिधापत्रिका क्रमांक",
    yes: "होय",
    no: "नाही",
    typeOfDisability: "दिव्यांगाचा प्रकार",
    back: "मागे",
    next: "पुढे",
    finish: "प्रस्तुत करा",
    currentAddressofHawker: "सध्याचा पत्ता",
    citySurveyNumber: "शहर सर्वेक्षण क्रमांक ",
    areaName: "क्षेत्राचे नाव ",
    landmarkName: "जवळची खुण",
    villageName: "गावाचे नाव ",
    cityName: "शहराचे नाव ",
    state: "राज्य ",
    pinCode: "पिन कोड ",
    lattitude: "अक्षांश ",
    logitude: "रेखांश ",
    permanentPostalAddressOfHawker: "कायमस्वरूपीचा/पत्रव्यवहाराचा पत्ता",
    permanentAddressAsTheCorrespondenceAddress:
      "पत्रव्यवहाराचा पत्ता म्हणून कायमचा पत्ता",
    citySurveyNumber: "शहर सर्वेक्षण क्रमांक",
    wardNo: "प्रभाग क्रमांक ",
    wardName: "प्रभागाचे नाव ",
    natureOfBusiness: "व्यवसायाचे स्वरूप ",
    hawkingDurationDaily: "पथविक्रीचा दैनिक कालावधी",
    item: "वस्तु",
    periodOfResidenceInMaharashtra: "महाराष्ट्रात राहण्याचा कालावधी",
    periodOfResidenceInPcmc: "पीसीएमसीमध्ये राहण्याचा कालावधी",
    bankName: "बँकेचे नाव",
    branchName: "शाखेचे नाव",
    bankAccountNo: "बँक खाते क्रमांक",
    ifscCode: "आयफएससी कोड",
    hawkerType: "पथविक्रीचा प्रकार",
    bankDetails: "बँक तपशील",
    documentUpload: "दस्तऐवज अपलोड करा",
    adharCard: "आधार कार्ड ",
    rationCard: "शिधापत्रिका ",
    disablityCretificatePhoto: "दिव्यांग प्रमाणपत्र ",
    otherDocumentPhoto: "इतर दस्तऐवज ",
    affidaviteOnRS100StampAttachement:
      "रु. १००/- चे स्टॅम्प पेपरवर प्रतिज्ञा पत्र ",
    panCard: "पॅन कार्ड ",
    waterConsumerNo: "पाणी ग्राहक क्र.",
    waterAmount: "रक्कम",
    proprtyAmount: "रक्कम",
    propertyTaxNumber: "मिळकत कर क्र.",
    tax: "कर",
    viewBill: "बिल पहा",
    pay: "बिल भरा",
    PropertyAndWaterTaxes: "कर",
    propertyTaxes: "मालमत्ता कर",
    waterTaxes: "पाणी कर ",
    pimpriChinchwad: "पिंपरी चिंचवड",
    maharashtra: "महाराष्ट्र",
    areaOfStreetvendor: "पथविक्री क्षेत्र",
    viewLocationOnMap: "नकाशावर स्थान पहा",
    voterNameYN: "अर्जदाराचे नाव मतदार यादीत आहे का?",
    voterId: "मतदार ओळखपत्र क्रमांक.",
    additionalLabour: "हॉकिन्सच्या ठिकाणी अतिरिक्त कामगार उपस्थित आहेत?",
    education: "शिक्षण",
    verfiyOtp: "ओटीपी तपसा",
    sendOTP: "ओटीपी पाठवा",
    aadhaarOtpVerified: "आधार ओटीपी यशस्वीरित्या सत्यापित",
    otpVerification: "ओटीपी पडताळणी",
    verifiyOTP: "ओटीपी सत्यापित करा",
    resendOTP: "ओटीपी पुन्हा पाठवा",
    sendOTPMessage:
      "तुमच्या नोंदणीकृत क्रमांकावर ६ अंकी वन-टाइम पासवर्ड पाठवला",
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा ",
    enterMName: "कृपया मधले  नाव भरा ",
    enterLName: "कृपया शेवटचे नाव भरा ",
    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",
    enterPinCode: "कृपया पिनकोड भरा",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterEmailAddress: "कृपया इलेक्ट्रॉनिक संदेश भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    enterRemarks: "कृपया टिप्पणी. द्या",
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",

    // Validations
    citySurveyNoValdation: "शहर सर्वेक्षण क्रमांक आवश्यक आहे !!!",
    citySurveyNoValdationA: "शहर सर्वेक्षण क्रमांक आवश्यक आहे !!!",
    areaNameValidation: "क्षेत्राचे नाव निवडणे आवश्यक आहे !!!",
    hawkingZoneNameValidation: "हॉकिंग झोनचे नाव निवडणे आवश्यक आहे !!!",
    titleValidation: "शीर्षक निवड आवश्यक आहे !!!",
    firstNameValidation: "पहिले नाव आवश्यक आहे !!!",
    middleNameValidation: "वडीलांचे/पतीचे नाव आवश्यक आहे !!!",
    lastNameValidation: "आडनाव आवश्यक आहे !!!",
    genderValidation: "लिंग निवड आवश्यक आहे !!!",
    religionValidation: "धर्म निवड आवश्यक आहे !!!",
    casteValidation: "जात निवड आवश्यक आहे !!!",
    subCasteValidation: "पोटजात निवड आवश्यक आहे !!!",
    dateOfBirthValidation: "जन्मतारीख आवश्यक आहे !!!",
    ageValidation: "वय आवश्यक आहे !!!",
    mobileNovalidation: "मोबाईल नंबर आवश्यक आहे !!!",
    rationCardNoValidation: "शिधापत्रिका क्रमांक आवश्यक आहे !!!",
    applicantTypeValidation: "अर्जदाराचे प्रकार निवड आवश्यक आहे !!!",
    emailIdValidation: "ई-मेल आयडी आवश्यक आहे !!!",
    emailIdValidationA: "कृपया वैध ई-मेल पत्ता प्रविष्ट करा !!!",
    landmarkNameValidation: "जवळची खूण नाव निवडणे  आवश्यक आहे ",
    villageNameValidation: "गावाचे नाव निवडणे आवश्यक आहे !!! ",
    cityNameValidation: "शहराचे नाव आवश्यक आहे !!!",
    stateNameValidation: "राज्याचे नाव आवश्यक आहे !!!",
    pinCodeValidation: "पिन कोड निवडणे आवश्यक आहे !!!",
    lattitudeValidation: "अक्षांश आवश्यक आहे !!!",
    logitudeValidation: "रेखांश आवश्यक आहे !!!",
    aadharNumberValidation: "आधार क्रमांक आवश्यक आहे !!!",
    propertyTaxNumberValidation: "मालमत्ता कर क्रमांक आवश्यक आहे !!!",
    waterConsumerNoValidation: "पाणी ग्राहक क्रमांक आवश्यक आहे !!!",
    proprtyTaxAmountNumberValidation: "मालमत्तेची रक्कम आवश्यक आहे !!!",
    waterTaxAmountValidation: "पाणी कराची रक्कम आवश्यक आहे !!!",
    streetvendorModeNameValidation:
      " पथविक्रीच्या व्यवसायाचे स्वरूप निवड आवश्यक आहे !!!",
    wardNameValidation: " प्रभाग नावाची निवड आवश्यक आहे  !!!",
    natureOfBusinessValidation: "व्यवसायाचे स्वरूप आवश्यक आहे !!!",
    hawkingDurationDailyValidation:
      "पथविक्रीचा दैनिक कालावधी निवड आवश्यक आहे !!!",
    hawkerTypeValidation: "पथविक्रीचा प्रकार निवड आवश्यक आहे !!!",
    itemValidation: "वस्तु निवड आवश्यक आहे !!!",
    educationValidation: "शिक्षण निवड आवश्यक आहे !!!",
    areaOfStreetvendorValidation: "पथविक्री क्षेत्रनाव आवश्यक आहे !!!",
    periodOfResidenceInPCMCValidation:
      "पीसीएमसीमध्ये राहण्याचा कालावधी आवश्यक आहे !!!",
    periodOfResidenceInMaharashtraValidation:
      "महाराष्ट्रात राहण्याचा कालावधी आवश्यक आहे !!!",
    voterNameYNValidation: "निवड आवश्यक आहे",
    voterIdValidation: "मतदार ओळखपत्र क्रमांक आवश्यक आहे !!!",
    bankMasterValidation: "बँकेचे नाव निवडणे आवश्यक आहे !!!",
    branchNameValidation: "शाखेचे नाव आवश्यक आहे !!!",
    bankAccountNoValidation: "बँक खाते क्रमांक आवश्यक आहे !!!",
    ifscCodeValidation: "IFSC कोड आवश्यक आहे !!!",
    aadhaarCardPhotoValidation: "आधार कार्ड आवश्यक आहे !!!",
    panCardPhotoValidation: "पॅन कार्ड आवश्यक आहे !!!",
    rationCardPhotoValidation: "शिधापत्रिका आवश्यक आहे !!!",
    disablityCertificatePhotoValidation: "दिव्यांग प्रमाणपत्र आवश्यक आहे !!!",
    affidaviteOnRS100StampAttacheValidation:
      "रु. १००/- चे स्टॅम्प पेपरवर प्रतिज्ञा पत्र आवश्यक आहे !!!",
    otherDocumentPhotoValidation: "इतर दस्तऐवज आवश्यक आहे !!!",
    // typeOfDisabilityValidation: "अपंगत्वाचा प्रकार आवश्यक आहे !!!",
    oldLicenseNoValidation: "जुना परवाना क्रमांक आवश्यक आहे !!!",
    oldLicenseDateValidation: "जुनी परवाना तारीख आवश्यक आहे !!!",
    documentUpload1: "दस्तऐवज अपलोड",
    documentUploadSuccessfully: "दस्तऐवज यशस्वीरित्या अपलोड केले !!!",
    delete: "हटवा",
    areYouWantDelete: "तुम्हाला खात्री आहे की तुम्हाला फाइल हटवायची आहे ?",
    fileDeletedSuccessfully: "फाइल यशस्वीरित्या हटवली !!!",
    fileIsSafe: "फाइल सुरक्षित आहे",
    somethingWentWrong: "काहीतरी चूक झाली ..!!!",
  },
};
